-- Create contest_ideas table for storing AI-generated contest ideas
-- Migration: 20241201000006_create_contest_ideas_table.sql

-- Create the contest_ideas table
CREATE TABLE IF NOT EXISTS contest_ideas (
  id BIGSERIAL PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  contest_id BIGINT REFERENCES contests(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  ai_generated BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_contest_ideas_user_id ON contest_ideas(user_id);
CREATE INDEX IF NOT EXISTS idx_contest_ideas_contest_id ON contest_ideas(contest_id);
CREATE INDEX IF NOT EXISTS idx_contest_ideas_ai_generated ON contest_ideas(ai_generated);

-- Enable Row Level Security (RLS)
ALTER TABLE contest_ideas ENABLE ROW LEVEL SECURITY;

-- Create policies for contest_ideas
CREATE POLICY "Users can manage their own contest ideas" ON contest_ideas
  FOR ALL USING (auth.uid() = user_id);

CREATE POLICY "Users can read their own contest ideas" ON contest_ideas
  FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own contest ideas" ON contest_ideas
  FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own contest ideas" ON contest_ideas
  FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own contest ideas" ON contest_ideas
  FOR DELETE USING (auth.uid() = user_id);

-- Create trigger to automatically update updated_at
CREATE TRIGGER update_contest_ideas_updated_at 
  BEFORE UPDATE ON contest_ideas 
  FOR EACH ROW 
  EXECUTE FUNCTION update_updated_at_column();

-- Add comments for documentation
COMMENT ON TABLE contest_ideas IS 'Stores AI-generated contest ideas';
COMMENT ON COLUMN contest_ideas.user_id IS 'Reference to the user who owns this idea';
COMMENT ON COLUMN contest_ideas.contest_id IS 'Reference to the contest this idea belongs to';
COMMENT ON COLUMN contest_ideas.title IS 'Idea title';
COMMENT ON COLUMN contest_ideas.description IS 'Idea description';
COMMENT ON COLUMN contest_ideas.ai_generated IS 'Whether this idea was generated by AI';
COMMENT ON COLUMN contest_ideas.created_at IS 'When the idea was created';
COMMENT ON COLUMN contest_ideas.updated_at IS 'When the idea was last updated'; 